### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by AmirGamilDev** [beemdevelopment/Aegis#1244]
Hello.

Excellent initiative.

Is there a way to verify that the build on the play store is produced from the code in this repo (a la Signal private messenger)? The verification in the readme suggests that the _certificate_ used for signing is the same but is this the same thing as the build being the same? Perhaps I'm missing something?

**Comment by alexbakker** [comment]
The section in the README you're referring to explains how you can verify that Aegis APK's were signed by us. Reproducible builds are something completely different and we don't support that currently.

**Comment by AmirGamilDev** [comment]
That's what I had understood. Is there a plan to include it on the roadmap? This would greatly increase the trust in the product.

**Comment by alexbakker** [comment]
Not currently. I'd first like to see a more detailed proposal and perhaps a proof of concept for this. Maintaining reproducible builds can be painful and it'd be good to have a general impression of what the impact on Aegis' build process would be.

**Comment by AmirGamilDev** [comment]
An excellent example is here:
https://github.com/signalapp/Signal-Android/tree/main/reproducible-builds

From the looks of things, I think it could be done with minimal impact to the build process once the work is carried out.

I believe this is truly important to be able to implement a TNO (Trust No One) solution.

**Comment by IzzySoft** [comment]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). We're just trying to establish Aegis there as well (see the linked issue). @alexbakker asked me to outline how we do that and what tools we use. Luckily, we've already set up that blog post I've just linked, explaining it – and meanwhile also [a wiki page](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Verification-Builder) on how you can set up your own verification server with the very same tools.

As for Aegis, it's almost reproducible, only some PNG files differ (again, please see the linked issue for details and hints on how to solve this). As we didn't yet succeed, the recipe is not yet online, so let me post it here in case one of you wants to try. These are the contents of `recipes/com.beemdevelopment.aegis.yml`:

```yaml
---
repository: https://github.com/beemdevelopment/Aegis.git
updates: releases
versions:
  - tag: v3.2
    apks:
      - apk_pattern: aegis-v.*\.apk
        apk_url: https://github.com/beemdevelopment/Aegis/releases/download/v3.2/aegis-v3.2.apk
        build:
          - chmod +x gradlew
          - ./gradlew assembleRelease
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_cpus:
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_timeout:
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages: []
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

And the diff in the linked issue is the only difference between the APK provided here and the one we've built using this recipe.
